version: "3"

services:

  nodejs:
    build: "./www"
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - /Users/sidnny/Projects/wtl/wtl-web/www:/home/node/www/

  # slackin:
  #   build: "./slackin"
  #   image: slackin
  #   container_name: slackin
  #   restart: unless-stopped
  #   networks:
  #     - app-network
  #   ports:
  #     - "3001:3001"

networks:
  app-network:
    driver: bridge
