version: "3"

services:

  nodejs:
    # build: "./www"
    # image: nodejs
    image: sidnny/wtl:latest
    container_name: nodejs
    restart: unless-stopped
    command: npm run dev
    networks:
      - app-network
    ports:
      - "3000:3000"
    volumes:
      - /Users/sidnny/Projects/wtl/wtl-web/www:/home/node/www/

networks:
  app-network:
    driver: bridge
